name: wgs

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.12
  - openjdk=17

  # Workflow
  - nextflow

  # Raw sequencing QC
  - fastqc
  - multiqc
  - seqkit

  # Alignment
  - bwa
  - bwa-mem2
  - samblaster

  # BAM / genomic utilities
  - samtools
  - bcftools
  - bedtools
  - htslib
  - mosdepth

  # Python
  - pyyaml
  - pytest
