name: wgs

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.12
  - openjdk=17
  - nextflow
  - fastqc
  - multiqc
  - bwa-mem2
  - samtools
  - bcftools
  - bedtools
  - seqkit
  - htslib
